### ISSUE TITLE
Edge triggered events in kqueue

### ISSUE THREAD

**Issue by Luminarys** [andrewjstone/amy#28]
After some testing with amy on kqueue supported platforms it seems as if events are level triggered (due to `EV_CLEAR` not being set), not edge triggered like epoll. Is this behavior intentional?

**Comment by andrewjstone** [comment]
Looking at the code, it seems you may be right. This is not intentional. Both modes should be edge triggered. I haven't really touched this code in quite a while though. Do you have a test case for this? I suppose one way to do it, would be to write to a socket and only read partially, then see if it gets triggered again on the next kqueue call.

**Comment by Luminarys** [comment]
The case I encountered it on was write notifications for any newly created socket. I can submit a test case later if needed.

**Comment by andrewjstone** [comment]
Ok, thanks. I'm working on a test case now. I'll get this fixed shortly.

**Comment by Luminarys** [comment]
I've made #31 to address this as well as update nix.

**Comment by andrewjstone** [comment]
Great. Thanks! I'll take a look. My test does indeed show that level triggering is used on kqueue based systems (OSX) but edge triggering is used on epoll based systems (linux).
